export const RESET_PAGE_ERROR = 'RESET_PAGE_ERROR';

export const SHOPS_REQUEST = 'SHOPS_REQUEST';
export const SHOPS_SUCCESS = 'SHOPS_SUCCESS';
export const SHOPS_FAILURE = 'SHOPS_FAILURE';

export const SHOP_REQUEST = 'SHOP_REQUEST';
export const SHOP_SUCCESS = 'SHOP_SUCCESS';
export const SHOP_FAILURE = 'SHOP_FAILURE';

export const SHOP_SERVICES_REQUEST = 'SHOP_SERVICES_REQUEST';
export const SHOP_SERVICES_SUCCESS = 'SHOP_SERVICES_SUCCESS';
export const SHOP_SERVICES_FAILURE = 'SHOP_SERVICES_FAILURE';

export const SHOP_SERVICE_REQUEST = 'SHOP_SERVICE_REQUEST';
export const SHOP_SERVICE_SUCCESS = 'SHOP_SERVICE_SUCCESS';
export const SHOP_SERVICE_FAILURE = 'SHOP_SERVICE_FAILURE';

export const SET_BOOKING_SERVICE = 'SET_BOOKING_SERVICE';
export const SET_BOOKING_CALENDAR_DATE = 'SET_BOOKING_CALENDAR_DATE';
export const SET_BOOKING_RANGE = 'SET_BOOKING_RANGE';

export const AVAILABLES_BOOKING_RANGES_REQUEST = 'AVAILABLES_BOOKING_RANGES_REQUEST';
export const AVAILABLES_BOOKING_RANGES_SUCCESS = 'AVAILABLES_BOOKING_RANGES_SUCCESS';
export const AVAILABLES_BOOKING_RANGES_FAILURE = 'AVAILABLES_BOOKING_RANGES_FAILURE';

export const BOOK_RANGE_REQUEST = 'BOOK_RANGE_REQUEST';
export const BOOK_RANGE_SUCCESS = 'BOOK_RANGE_SUCCESS';
export const BOOK_RANGE_FAILURE = 'BOOK_RANGE_FAILURE';

export const SHOW_MODAL_LOGIN = 'SHOW_MODAL_LOGIN';
export const HIDE_MODAL_LOGIN = 'HIDE_MODAL_LOGIN';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const ME_REQUEST = 'ME_REQUEST';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAILURE = 'ME_FAILURE';

export const SET_USER_TOKEN = 'SET_USER_TOKEN';
