export const SHOPS_REQUEST = 'SHOPS_REQUEST';
export const SHOPS_SUCCESS = 'SHOPS_SUCCESS';
export const SHOPS_FAILURE = 'SHOPS_FAILURE';

export const SHOP_REQUEST = 'SHOP_REQUEST';
export const SHOP_SUCCESS = 'SHOP_SUCCESS';
export const SHOP_FAILURE = 'SHOP_FAILURE';

export const SHOP_SERVICES_REQUEST = 'SHOP_SERVICES_REQUEST';
export const SHOP_SERVICES_SUCCESS = 'SHOP_SERVICES_SUCCESS';
export const SHOP_SERVICES_FAILURE = 'SHOP_SERVICES_FAILURE';

export const SHOP_SERVICE_REQUEST = 'SHOP_SERVICE_REQUEST';
export const SHOP_SERVICE_SUCCESS = 'SHOP_SERVICE_SUCCESS';
export const SHOP_SERVICE_FAILURE = 'SHOP_SERVICE_FAILURE';

export const SET_BOOKING_DATA = 'SET_BOOKING_DATA';

export const REQUEST_BOOKING_RANGES = 'REQUEST_BOOKING_RANGES';
export const RANGES_REQUEST = 'RANGES_REQUEST';
export const RANGES_SUCCESS = 'RANGES_SUCCESS';
export const RANGES_FAILURE = 'RANGES_FAILURE';

export const SET_BOOKING_RANGE = 'SET_BOOKING_RANGE';
