export const SHOPS_REQUEST = 'SHOPS_REQUEST';
export const SHOPS_SUCCESS = 'SHOPS_SUCCESS';
export const SHOPS_FAILURE = 'SHOPS_FAILURE';

export const SHOP_REQUEST = 'SHOP_REQUEST';
export const SHOP_SUCCESS = 'SHOP_SUCCESS';
export const SHOP_FAILURE = 'SHOP_FAILURE';

export const SHOP_SERVICES_REQUEST = 'SHOP_SERVICES_REQUEST';
export const SHOP_SERVICES_SUCCESS = 'SHOP_SERVICES_SUCCESS';
export const SHOP_SERVICES_FAILURE = 'SHOP_SERVICES_FAILURE';

export const SHOP_SERVICE_REQUEST = 'SHOP_SERVICE_REQUEST';
export const SHOP_SERVICE_SUCCESS = 'SHOP_SERVICE_SUCCESS';
export const SHOP_SERVICE_FAILURE = 'SHOP_SERVICE_FAILURE';

export const SET_BOOKING_SERVICE = 'SET_BOOKING_SERVICE';
export const SET_BOOKING_CALENDAR_DATE = 'SET_BOOKING_CALENDAR_DATE';
export const SET_BOOKING_VIEWED_DATE = 'SET_BOOKING_VIEWED_DATE';

export const BOOKING_RANGES_REQUEST = 'BOOKING_RANGES_REQUEST';
export const BOOKING_RANGES_SUCCESS = 'BOOKING_RANGES_SUCCESS';
export const BOOKING_RANGES_FAILURE = 'BOOKING_RANGES_FAILURE';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const ME_REQUEST = 'ME_REQUEST';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAILURE = 'ME_FAILURE';

export const SET_USER_TOKEN = 'SET_USER_TOKEN';





